// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: countries.proto

package countries

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (c *Code) UnmarshalGQL(v interface{}) error {
	code, ok := v.(string)
	if ok {
		*c = Code(Code_value[code])
		return nil
	}
	return fmt.Errorf("cannot unmarshal Code enum")
}

func (c Code) MarshalGQL(w io.Writer) {
	fmt.Fprintf(w, "%q", c.String())
}
